/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SettingsImport } from './routes/settings'
import { Route as LoginImport } from './routes/login'
import { Route as CreateAccountImport } from './routes/create-account'
import { Route as TargetSevenLetterImport } from './routes/target/seven-letter'
import { Route as TargetNineLetterImport } from './routes/target/nine-letter'

// Create Virtual Routes

const AboutLazyImport = createFileRoute('/about')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const AboutLazyRoute = AboutLazyImport.update({
  path: '/about',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/about.lazy').then((d) => d.Route))

const SettingsRoute = SettingsImport.update({
  path: '/settings',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const CreateAccountRoute = CreateAccountImport.update({
  path: '/create-account',
  getParentRoute: () => rootRoute,
} as any)

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const TargetSevenLetterRoute = TargetSevenLetterImport.update({
  path: '/target/seven-letter',
  getParentRoute: () => rootRoute,
} as any)

const TargetNineLetterRoute = TargetNineLetterImport.update({
  path: '/target/nine-letter',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/create-account': {
      id: '/create-account'
      path: '/create-account'
      fullPath: '/create-account'
      preLoaderRoute: typeof CreateAccountImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutLazyImport
      parentRoute: typeof rootRoute
    }
    '/target/nine-letter': {
      id: '/target/nine-letter'
      path: '/target/nine-letter'
      fullPath: '/target/nine-letter'
      preLoaderRoute: typeof TargetNineLetterImport
      parentRoute: typeof rootRoute
    }
    '/target/seven-letter': {
      id: '/target/seven-letter'
      path: '/target/seven-letter'
      fullPath: '/target/seven-letter'
      preLoaderRoute: typeof TargetSevenLetterImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexLazyRoute,
  CreateAccountRoute,
  LoginRoute,
  SettingsRoute,
  AboutLazyRoute,
  TargetNineLetterRoute,
  TargetSevenLetterRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/create-account",
        "/login",
        "/settings",
        "/about",
        "/target/nine-letter",
        "/target/seven-letter"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/create-account": {
      "filePath": "create-account.tsx"
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/settings": {
      "filePath": "settings.tsx"
    },
    "/about": {
      "filePath": "about.lazy.tsx"
    },
    "/target/nine-letter": {
      "filePath": "target/nine-letter.tsx"
    },
    "/target/seven-letter": {
      "filePath": "target/seven-letter.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
